### Create Account
POST http://localhost:3333/accounts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0ODY0OGI2Yi1mYjAyLTQzMTktODExYS1lYzc3NGFiZWIwOTYiLCJpYXQiOjE3Mjg5MjA3MTN9.IGrDdkMQg68A7FrmDO2Uri9drk6KCoOtSPTNLAq1suQ

{
    "bank": "Nubank",
    "branch": "0001",
    "account_number": "123456-8"
}

### Get All Accounts
GET http://localhost:3333/accounts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0ODY0OGI2Yi1mYjAyLTQzMTktODExYS1lYzc3NGFiZWIwOTYiLCJpYXQiOjE3Mjg5MjA3MTN9.IGrDdkMQg68A7FrmDO2Uri9drk6KCoOtSPTNLAq1suQ
