### Create new account
POST http://localhost:3333/accounts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1ZTQzYTg3MS04YWM5LTRiMWUtYjJjNi00OWEzOGY1MmVmODQiLCJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJpYXQiOjE3MTM4OTgwODMsImV4cCI6MTcxMzg5ODk4M30.oIr1Osng6dRUhGoGZGoS6xwKiuOl-elmLbNYlVXFBcU

{
  "bank": "Nubank",
  "branch": "12345",
  "accountNumber": "123456"
}